/*
  Implement a class `Todo` having below methods
    - add(todo): adds todo to list of todos
    - remove(indexOfTodo): remove todo from list of todos
    - update(index, updatedTodo): update todo at given index
    - getAll: returns all todos
    - get(indexOfTodo): returns todo at given index
    - clear: deletes all todos

  Once you've implemented the logic, test your code by running
  - `npm run test-todo-list`
*/


let tasks;

class Todo {
    constructor() {
        tasks = [];
    }

    add(task) {
        tasks.push(task);
    }

    remove(index) {
        tasks.splice(index, 1);
    }

    update(index, task) {
        tasks[index] = task;
    }

    getAll() {
        return tasks;
    }

    get(index) {
        return tasks[index];
    }

    clear() {
        tasks = [];
    }
}





// ----------------------------------------------------------------
//Test Cases given below isgenerated by Chat GPT
// ----------------------------------------------------------------




const todoList = new Todo();

// Test adding todos
todoList.add("Buy groceries");
todoList.add("Finish homework");
todoList.add("Go for a run");

console.log(todoList.getAll());
// Expected output: ["Buy groceries", "Finish homework", "Go for a run"]

// Test removing a todo
todoList.remove(1); // Remove the todo at index 1 (which is "Finish homework")

console.log(todoList.getAll());
// Expected output: ["Buy groceries", "Go for a run"]

// Test updating a todo
todoList.update(0, "Buy new shoes"); // Update the todo at index 0

console.log(todoList.get(0));
// Expected output: "Buy new shoes"

// Test getting a specific todo
console.log(todoList.get(1));
// Expected output: "Go for a run"

// Test clearing all todos
todoList.clear();

console.log(todoList.getAll());
// Expected output: []




module.exports = Todo;
